[
	{
		id: 21,
		nome_servico: "Limpeza Comum",
		cliente: {
			nome_completo: "J\u00falia Alessandra Moura",
			reputacao: 5,
			foto_usuario: "public/WmTOCPkkToH2fi32aZFyTezEIXEgPruRneWGzVEL.jpg",
		},
		data_atendimento: "2023-01-25T17:00:00Z",
		tempo_atendimento: 7,
		valor_diarista: 63.9,
		preco: 63.9,
		logradouro: "Rua Igua\u00e7u",
		numero: "110",
		complemento: "casa 1",
		bairro: "Nossa Senhora das Gra\u00e7as",
		cidade: "Uberl\u00e2ndia",
		estado: "MG",
		quantidade_quartos: 2,
		quantidade_salas: 1,
		quantidade_cozinhas: 1,
		quantidade_banheiros: 1,
		quantidade_quintais: 1,
		quantidade_outros: 0,
		avaliacoes_cliente: [],
		links: [
			{
				type: "POST",
				rel: "candidatar_diaria",
				uri: "http://192.168.100.11:8000/api/diarias/21/candidatos",
			},
		],
	},
	{
		id: 22,
		nome_servico: "Limpeza Comum",
		cliente: {
			nome_completo: "J\u00falia Alessandra Moura",
			reputacao: 5,
			foto_usuario: "public/WmTOCPkkToH2fi32aZFyTezEIXEgPruRneWGzVEL.jpg",
		},
		data_atendimento: "2023-02-04T17:00:00Z",
		tempo_atendimento: 7,
		valor_diarista: 63.9,
		preco: 63.9,
		logradouro: "Rua Igua\u00e7u",
		numero: "110",
		complemento: "casa 1",
		bairro: "Nossa Senhora das Gra\u00e7as",
		cidade: "Uberl\u00e2ndia",
		estado: "MG",
		quantidade_quartos: 2,
		quantidade_salas: 1,
		quantidade_cozinhas: 1,
		quantidade_banheiros: 1,
		quantidade_quintais: 1,
		quantidade_outros: 0,
		avaliacoes_cliente: [],
		links: [
			{
				type: "POST",
				rel: "candidatar_diaria",
				uri: "http://192.168.100.11:8000/api/diarias/22/candidatos",
			},
		],
	},
	{
		id: 24,
		nome_servico: "Limpeza Comum",
		cliente: {
			nome_completo: "J\u00falia Alessandra Moura",
			reputacao: 5,
			foto_usuario: "public/WmTOCPkkToH2fi32aZFyTezEIXEgPruRneWGzVEL.jpg",
		},
		data_atendimento: "2023-02-26T17:00:00Z",
		tempo_atendimento: 7,
		valor_diarista: 63.9,
		preco: 63.9,
		logradouro: "Rua Igua\u00e7u",
		numero: "110",
		complemento: "casa 1",
		bairro: "Nossa Senhora das Gra\u00e7as",
		cidade: "Uberl\u00e2ndia",
		estado: "MG",
		quantidade_quartos: 2,
		quantidade_salas: 1,
		quantidade_cozinhas: 1,
		quantidade_banheiros: 1,
		quantidade_quintais: 1,
		quantidade_outros: 0,
		avaliacoes_cliente: [],
		links: [
			{
				type: "POST",
				rel: "candidatar_diaria",
				uri: "http://192.168.100.11:8000/api/diarias/24/candidatos",
			},
		],
	},
];
